{{- if .Values.accessKey.secretValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.accessKey.secretName }}
  labels:
    {{- include "rhokp.selectorLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  {{ .Values.accessKey.secretKey }}: {{ .Values.accessKey.secretValue | quote }}
{{- end }}
