{{- if .Values.imagePullSecret.dockerPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "rhokp.selectorLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecret.dockerServer .Values.imagePullSecret.dockerUsername .Values.imagePullSecret.dockerPassword (printf "%s:%s" .Values.imagePullSecret.dockerUsername .Values.imagePullSecret.dockerPassword | b64enc) | quote }}
{{- end }}
